name: test

on:
  pull_request:
    branches: dev

jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: test run
        id: build-image
        run: |
          echo "MYSQL_URI=${{ secrets.MYSQL_URI }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
          cat .env
